### PR TITLE
init project

### PR DESCRIPTION
**Pull request by hoangdv99**
## Related Tickets:
- [#40575](https://edu-redmine.sun-asterisk.vn/issues/40575)

## WHAT this PR does?

init project

## Notes Impacted Areas:
- N/A.

## Attachments:
- N/A.

### CODE REVIEW

**Comment by hoangdv99** [comment]
ready

**Comment by hoangdv99** [comment]
ready

**Comment by hoangdv99** [comment]
ready

**Comment by hoangdv99** [comment]
ready

**Comment by hoangdv99** [comment]
ready

**Review by huyenttm-0901 — COMMENTED** [review]
em copy hết project ra ngoài folder e-commerce nhé

**Comment by hoangdv99** [comment]
ready

**Review by huyenttm-0901 — COMMENTED** [review]
fail CI

**Comment by hoangdv99** [comment]
ready

**Review by huyenttm-0901 — APPROVED** [review]

**Pull request merged**
